# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/UI/Analyzer.ui'
#
# Created: Wed Mar  5 15:43:23 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(630, 654)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 80, 231, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.filePath_txt = QtGui.QLineEdit(self.centralwidget)
        self.filePath_txt.setGeometry(QtCore.QRect(40, 30, 211, 27))
        self.filePath_txt.setObjectName(_fromUtf8("filePath_txt"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 411, 17))
        self.label.setStyleSheet(_fromUtf8("font: bold;"))
        self.label.setObjectName(_fromUtf8("label"))
        self.browse_button = QtGui.QPushButton(self.centralwidget)
        self.browse_button.setGeometry(QtCore.QRect(270, 30, 98, 27))
        self.browse_button.setObjectName(_fromUtf8("browse_button"))
        self.gdf_rb = QtGui.QRadioButton(self.centralwidget)
        self.gdf_rb.setGeometry(QtCore.QRect(40, 60, 116, 22))
        self.gdf_rb.setObjectName(_fromUtf8("gdf_rb"))
        self.csv_rb = QtGui.QRadioButton(self.centralwidget)
        self.csv_rb.setGeometry(QtCore.QRect(110, 60, 116, 22))
        self.csv_rb.setChecked(True)
        self.csv_rb.setObjectName(_fromUtf8("csv_rb"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 111, 25))
        self.label_2.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.removeNoise_cb = QtGui.QCheckBox(self.centralwidget)
        self.removeNoise_cb.setGeometry(QtCore.QRect(40, 120, 131, 30))
        self.removeNoise_cb.setChecked(True)
        self.removeNoise_cb.setObjectName(_fromUtf8("removeNoise_cb"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 100, 141, 25))
        self.label_3.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.smoothSignal_cb = QtGui.QCheckBox(self.centralwidget)
        self.smoothSignal_cb.setGeometry(QtCore.QRect(350, 120, 131, 30))
        self.smoothSignal_cb.setObjectName(_fromUtf8("smoothSignal_cb"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(390, 80, 231, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 80, 151, 20))
        self.label_4.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 150, 151, 20))
        self.label_5.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(390, 150, 231, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 150, 231, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 111, 20))
        self.label_6.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.featureSelection_box = QtGui.QComboBox(self.centralwidget)
        self.featureSelection_box.setGeometry(QtCore.QRect(130, 180, 211, 27))
        self.featureSelection_box.setObjectName(_fromUtf8("featureSelection_box"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 220, 231, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(360, 220, 261, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(250, 220, 151, 20))
        self.label_7.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 121, 20))
        self.label_8.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.classifierSelection_box = QtGui.QComboBox(self.centralwidget)
        self.classifierSelection_box.setGeometry(QtCore.QRect(130, 250, 211, 27))
        self.classifierSelection_box.setObjectName(_fromUtf8("classifierSelection_box"))
        self.train_button = QtGui.QPushButton(self.centralwidget)
        self.train_button.setGeometry(QtCore.QRect(230, 300, 211, 27))
        self.train_button.setObjectName(_fromUtf8("train_button"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 320, 121, 20))
        self.label_9.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.trainresult_txt = QtGui.QLabel(self.centralwidget)
        self.trainresult_txt.setGeometry(QtCore.QRect(30, 340, 27, 17))
        self.trainresult_txt.setStyleSheet(_fromUtf8("font: bold;"))
        self.trainresult_txt.setObjectName(_fromUtf8("trainresult_txt"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(10, 380, 611, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(10, 390, 611, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 440, 171, 17))
        self.label_11.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.testDataFile_txt = QtGui.QLineEdit(self.centralwidget)
        self.testDataFile_txt.setGeometry(QtCore.QRect(60, 460, 171, 27))
        self.testDataFile_txt.setText(_fromUtf8(""))
        self.testDataFile_txt.setObjectName(_fromUtf8("testDataFile_txt"))
        self.csvTestfile_rb = QtGui.QRadioButton(self.centralwidget)
        self.csvTestfile_rb.setGeometry(QtCore.QRect(130, 490, 116, 22))
        self.csvTestfile_rb.setObjectName(_fromUtf8("csvTestfile_rb"))
        self.GDFtestFile_rb = QtGui.QRadioButton(self.centralwidget)
        self.GDFtestFile_rb.setGeometry(QtCore.QRect(60, 490, 116, 22))
        self.GDFtestFile_rb.setObjectName(_fromUtf8("GDFtestFile_rb"))
        self.testDataBrowsebutton = QtGui.QPushButton(self.centralwidget)
        self.testDataBrowsebutton.setGeometry(QtCore.QRect(240, 460, 98, 27))
        self.testDataBrowsebutton.setObjectName(_fromUtf8("testDataBrowsebutton"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(40, 520, 171, 17))
        self.label_13.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(360, 410, 121, 20))
        self.label_14.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 410, 121, 20))
        self.label_15.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(340, 420, 20, 161))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.testresult_txt = QtGui.QLabel(self.centralwidget)
        self.testresult_txt.setGeometry(QtCore.QRect(380, 430, 121, 31))
        self.testresult_txt.setObjectName(_fromUtf8("testresult_txt"))
        self.test_button = QtGui.QPushButton(self.centralwidget)
        self.test_button.setGeometry(QtCore.QRect(240, 590, 210, 27))
        self.test_button.setObjectName(_fromUtf8("test_button"))
        self.fulldatatest_rb = QtGui.QRadioButton(self.centralwidget)
        self.fulldatatest_rb.setGeometry(QtCore.QRect(70, 540, 116, 22))
        self.fulldatatest_rb.setObjectName(_fromUtf8("fulldatatest_rb"))
        self.twentytest_rb = QtGui.QRadioButton(self.centralwidget)
        self.twentytest_rb.setGeometry(QtCore.QRect(70, 560, 116, 22))
        self.twentytest_rb.setObjectName(_fromUtf8("twentytest_rb"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(420, 0, 111, 40))
        self.label_12.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.subject_name = QtGui.QLabel(self.centralwidget)
        self.subject_name.setGeometry(QtCore.QRect(430, 30, 191, 20))
        self.subject_name.setObjectName(_fromUtf8("subject_name"))
        self.done1 = QtGui.QLabel(self.centralwidget)
        self.done1.setGeometry(QtCore.QRect(510, 110, 81, 31))
        self.done1.setText(_fromUtf8(""))
        self.done1.setObjectName(_fromUtf8("done1"))
        self.done2 = QtGui.QLabel(self.centralwidget)
        self.done2.setGeometry(QtCore.QRect(500, 180, 81, 31))
        self.done2.setText(_fromUtf8(""))
        self.done2.setObjectName(_fromUtf8("done2"))
        self.done3 = QtGui.QLabel(self.centralwidget)
        self.done3.setGeometry(QtCore.QRect(510, 250, 81, 31))
        self.done3.setText(_fromUtf8(""))
        self.done3.setObjectName(_fromUtf8("done3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BrainGizer Analyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.filePath_txt.setText(QtGui.QApplication.translate("MainWindow", "/media/Work/GraduationProject/Analysier/TrainingData/[2014-03-01 16-52-36] Moahmed Nour.csv", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select Training data file (<span style=\" font-size:8pt; font-weight:400;\">please select file type before selcting the file</span>)</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_button.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.gdf_rb.setText(QtGui.QApplication.translate("MainWindow", "GDF", None, QtGui.QApplication.UnicodeUTF8))
        self.csv_rb.setText(QtGui.QApplication.translate("MainWindow", "CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Noise Removal </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.removeNoise_cb.setText(QtGui.QApplication.translate("MainWindow", "Remove Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Signal Smoothing</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothSignal_cb.setText(QtGui.QApplication.translate("MainWindow", "Smooth Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Signal Enhancment </p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Feature Exctraction</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select Method</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Classification</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select Classifier</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.train_button.setText(QtGui.QApplication.translate("MainWindow", "Train", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Training Results</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.trainresult_txt.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">N/A</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select Test data file</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.csvTestfile_rb.setText(QtGui.QApplication.translate("MainWindow", "CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.GDFtestFile_rb.setText(QtGui.QApplication.translate("MainWindow", "GDF", None, QtGui.QApplication.UnicodeUTF8))
        self.testDataBrowsebutton.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Test using training data</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Test Results</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Test Method</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.testresult_txt.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.test_button.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.fulldatatest_rb.setText(QtGui.QApplication.translate("MainWindow", "Full data", None, QtGui.QApplication.UnicodeUTF8))
        self.twentytest_rb.setText(QtGui.QApplication.translate("MainWindow", "20% testing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Subject Name</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.subject_name.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))

